package report

import (
    "bytes"
    "fmt"
    "strings"
    "text/template"
    "time"

    "semantic-analyzer/internal/domain"
)

// Generator creates human-readable reports
type Generator struct {
    templates   map[string]*template.Template
    config      ReportConfig
}

// ReportConfig holds report generation configuration
type ReportConfig struct {
    Format        string            `json:"format" yaml:"format"` // "text", "html", "markdown"
    TemplatePath  string            `json:"template_path" yaml:"template_path"`
    IncludeSections []string        `json:"include_sections" yaml:"include_sections"`
    Style         map[string]string `json:"style" yaml:"style"`
    MaxMarkers    int               `json:"max_markers" yaml:"max_markers"`
    ShowConfidence bool             `json:"show_confidence" yaml:"show_confidence"`
    ShowPositions  bool             `json:"show_positions" yaml:"show_positions"`
    GroupByLevel   bool             `json:"group_by_level" yaml:"group_by_level"`
    SortBy         string           `json:"sort_by" yaml:"sort_by"` // "confidence", "level", "type", "position"
}

// NewGenerator creates a new report generator
func NewGenerator(cfg ReportConfig) *Generator {
    g := &Generator{
        templates: make(map[string]*template.Template),
        config:    cfg,
    }
    
    g.initialize()
    return g
}

// initialize sets up the report generator
func (g *Generator) initialize() {
    // Load default templates
    g.loadDefaultTemplates()
    
    // Load custom template if specified
    if g.config.TemplatePath != "" {
        g.loadCustomTemplate()
    }
}

// loadDefaultTemplates loads default templates
func (g *Generator) loadDefaultTemplates() {
    // Text template
    textTemplate := `SEMANTIC ANALYSIS REPORT
=======================

Transcript: {{.Transcript.Source}}
Analysis Time: {{.Timestamp.Format "2006-01-02 15:04:05"}}
Processing Time: {{printf "%.2f" .Statistics.ProcessingTime}} seconds

SUMMARY
-------
Total Markers: {{.Statistics.TotalMarkers}}
Atomic Markers: {{.Statistics.AtomicMarkers}}
Composite Markers: {{.Statistics.CompositeMarkers}}
Average Confidence: {{printf "%.2f" .Statistics.AverageConfidence}}

{{if .Statistics.MarkerTypes}}
Marker Types:
{{range $type, $count := .Statistics.MarkerTypes}}  {{$type}}: {{$count}}
{{end}}
{{end}}

{{if .Markers}}
DETAILED FINDINGS
-----------------
{{range $level, $markers := .MarkersByLevel}}{{if $markers}}
Level {{$level}} Markers:
{{range $markers}}{{if $.ShowConfidence}}[{{printf "%.2f" .Confidence}}] {{end}}{{.Type}}: "{{.TextSpan}}"
{{if $.ShowPositions}}  Position: {{.Start}}-{{.End}}
{{end}}{{if .Context}}  Context: {{.Context}}
{{end}}{{if .RuleID}}  Detected by: {{.RuleID}}
{{end}}
{{end}}{{end}}{{end}}
{{end}}

{{if .AuditSummary}}
PROCESSING DETAILS
------------------
Total Audit Events: {{.AuditSummary.TotalEvents}}
Analysis Stages: {{.AuditSummary.StageCount}}
{{if .AuditSummary.Errors}}Errors: {{.AuditSummary.Errors}}
{{end}}
{{end}}

Report generated by Semantic Analyzer v{{.Version}}
`
    
    tmpl, err := template.New("text_report").Parse(textTemplate)
    if err == nil {
        g.templates["text"] = tmpl
    }
    
    // Markdown template
    markdownTemplate := `# Semantic Analysis Report

## Transcript Information
- **Source**: {{.Transcript.Source}}
- **Analysis Time**: {{.Timestamp.Format "2006-01-02 15:04:05"}}
- **Processing Time**: {{printf "%.2f" .Statistics.ProcessingTime}} seconds

## Summary
- **Total Markers**: {{.Statistics.TotalMarkers}}
- **Atomic Markers**: {{.Statistics.AtomicMarkers}}
- **Composite Markers**: {{.Statistics.CompositeMarkers}}
- **Average Confidence**: {{printf "%.2f" .Statistics.AverageConfidence}}

{{if .Statistics.MarkerTypes}}
### Marker Types
| Type | Count |
|------|-------|
{{range $type, $count := .Statistics.MarkerTypes}}| {{$type}} | {{$count}} |
{{end}}
{{end}}

{{if .Markers}}
## Detailed Findings
{{range $level, $markers := .MarkersByLevel}}{{if $markers}}
### Level {{$level}} Markers
{{range $markers}}
{{if $.ShowConfidence}}**Confidence**: {{printf "%.2f" .Confidence}}  {{end}}
**Type**: {{.Type}}
**Text**: "{{.TextSpan}}"
{{if $.ShowPositions}}**Position**: {{.Start}}-{{.End}}
{{end}}{{if .Context}}**Context**: {{.Context}}
{{end}}{{if .RuleID}}**Detected by**: {{.RuleID}}
{{end}}
---
{{end}}{{end}}{{end}}
{{end}}

{{if .AuditSummary}}
## Processing Details
- **Total Audit Events**: {{.AuditSummary.TotalEvents}}
- **Analysis Stages**: {{.AuditSummary.StageCount}}
{{if .AuditSummary.Errors}}- **Errors**: {{.AuditSummary.Errors}}
{{end}}
{{end}}

*Report generated by Semantic Analyzer v{{.Version}}*
`
    
    tmpl, err = template.New("markdown_report").Parse(markdownTemplate)
    if err == nil {
        g.templates["markdown"] = tmpl
    }
}

// loadCustomTemplate loads custom template from file
func (g *Generator) loadCustomTemplate() {
    // Implementation for loading custom templates
    // This would read from g.config.TemplatePath
}

// GenerateReport generates a human-readable report
func (g *Generator) GenerateReport(result *domain.AnalysisResult) ([]byte, error) {
    // Prepare data for template
    data := g.prepareReportData(result)
    
    // Get appropriate template
    templateKey := g.config.Format
    if templateKey == "" {
        templateKey = "text"
    }
    
    tmpl, exists := g.templates[templateKey]
    if !exists {
        return nil, fmt.Errorf("no template for format: %s", templateKey)
    }
    
    // Execute template
    var buf bytes.Buffer
    if err := tmpl.Execute(&buf, data); err != nil {
        return nil, fmt.Errorf("failed to execute template: %w", err)
    }
    
    return buf.Bytes(), nil
}

// prepareReportData prepares data for the report template
func (g *Generator) prepareReportData(result *domain.AnalysisResult) map[string]interface{} {
    data := make(map[string]interface{})
    
    // Basic information
    data["Timestamp"] = result.Timestamp
    data["Version"] = result.Version
    data["ConfigHash"] = result.ConfigHash
    
    // Transcript information
    if result.Transcript != nil {
        data["Transcript"] = map[string]interface{}{
            "Source":    result.Transcript.Source,
            "WordCount": result.Transcript.TokenCount,
            "Sentences": len(result.Transcript.Sentences),
        }
    }
    
    // Statistics
    data["Statistics"] = result.Statistics
    
    // Prepare markers for display
    markers := g.prepareMarkersForDisplay(result.Markers)
    data["Markers"] = markers
    
    // Group markers by level if requested
    if g.config.GroupByLevel {
        markersByLevel := make(map[int][]domain.Marker)
        for _, marker := range markers {
            markersByLevel[marker.Level] = append(markersByLevel[marker.Level], marker)
        }
        data["MarkersByLevel"] = markersByLevel
    }
    
    // Audit summary
    if result.AuditTrail != nil {
        auditSummary := g.prepareAuditSummary(result.AuditTrail)
        data["AuditSummary"] = auditSummary
    }
    
    // Config settings for template
    data["ShowConfidence"] = g.config.ShowConfidence
    data["ShowPositions"] = g.config.ShowPositions
    
    return data
}

// prepareMarkersForDisplay prepares markers for display in report
func (g *Generator) prepareMarkersForDisplay(markers []domain.Marker) []domain.Marker {
    // Sort markers
    sorted := make([]domain.Marker, len(markers))
    copy(sorted, markers)
    g.sortMarkers(sorted)
    
    // Limit number of markers if specified
    if g.config.MaxMarkers > 0 && len(sorted) > g.config.MaxMarkers {
        sorted = sorted[:g.config.MaxMarkers]
    }
    
    return sorted
}

// sortMarkers sorts markers according to configuration
func (g *Generator) sortMarkers(markers []domain.Marker) {
    sortBy := g.config.SortBy
    if sortBy == "" {
        sortBy = "confidence"
    }
    
    // Simple bubble sort for clarity
    for i := 0; i < len(markers); i++ {
        for j := i + 1; j < len(markers); j++ {
            shouldSwap := false
            
            switch sortBy {
            case "confidence":
                shouldSwap = markers[i].Confidence < markers[j].Confidence
            case "level":
                shouldSwap = markers[i].Level < markers[j].Level
            case "type":
                shouldSwap = markers[i].Type > markers[j].Type
            case "position":
                shouldSwap = markers[i].Start > markers[j].Start
            }
            
            if shouldSwap {
                markers[i], markers[j] = markers[j], markers[i]
            }
        }
    }
}

// prepareAuditSummary prepares audit trail summary
func (g *Generator) prepareAuditSummary(auditTrail *domain.AuditTrail) map[string]interface{} {
    if auditTrail == nil {
        return nil
    }
    
    stageCount := make(map[string]int)
    errorCount := 0
    
    for _, event := range auditTrail.Events {
        stageCount[event.Stage]++
        if event.Error != "" {
            errorCount++
        }
    }
    
    return map[string]interface{}{
        "TotalEvents": len(auditTrail.Events),
        "StageCount":  len(stageCount),
        "Errors":      errorCount,
        "StartTime":   auditTrail.StartTime.Format("15:04:05"),
        "EndTime":     auditTrail.EndTime.Format("15:04:05"),
        "Duration":    auditTrail.EndTime.Sub(auditTrail.StartTime).String(),
    }
}

// GenerateSummary generates a brief summary report
func (g *Generator) GenerateSummary(result *domain.AnalysisResult) string {
    var summary strings.Builder
    
    summary.WriteString(fmt.Sprintf("Analysis Summary for: %s\n", result.Transcript.Source))
    summary.WriteString(fmt.Sprintf("Total Markers: %d\n", result.Statistics.TotalMarkers))
    summary.WriteString(fmt.Sprintf("Atomic: %d, Composite: %d\n", 
        result.Statistics.AtomicMarkers, result.Statistics.CompositeMarkers))
    summary.WriteString(fmt.Sprintf("Average Confidence: %.2f\n", result.Statistics.AverageConfidence))
    
    // Top 3 marker types
    if len(result.Statistics.MarkerTypes) > 0 {
        summary.WriteString("Top Marker Types:\n")
        count := 0
        for t, c := range result.Statistics.MarkerTypes {
            summary.WriteString(fmt.Sprintf("  %s: %d\n", t, c))
            count++
            if count >= 3 {
                break
            }
        }
    }
    
    // Processing time
    summary.WriteString(fmt.Sprintf("Processing Time: %.2fs\n", result.Statistics.ProcessingTime))
    
    return summary.String()
}

// GenerateHTMLReport generates an HTML formatted report
func (g *Generator) GenerateHTMLReport(result *domain.AnalysisResult) ([]byte, error) {
    // Simple HTML template
    htmlTemplate := `<!DOCTYPE html>
<html>
<head>
    <title>Semantic Analysis Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1 { color: #333; }
        h2 { color: #666; margin-top: 30px; }
        table { border-collapse: collapse; width: 100%; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .confidence-high { color: green; }
        .confidence-medium { color: orange; }
        .confidence-low { color: red; }
        .marker { margin: 10px 0; padding: 10px; border-left: 4px solid #ccc; }
        .level-1 { border-color: #4CAF50; }
        .level-2 { border-color: #2196F3; }
        .level-3 { border-color: #FF9800; }
        .level-4 { border-color: #9C27B0; }
        .level-5 { border-color: #F44336; }
    </style>
</head>
<body>
    <h1>Semantic Analysis Report</h1>
    
    <h2>Summary</h2>
    <table>
        <tr><th>Transcript Source</th><td>{{.Transcript.Source}}</td></tr>
        <tr><th>Analysis Time</th><td>{{.Timestamp.Format "2006-01-02 15:04:05"}}</td></tr>
        <tr><th>Processing Time</th><td>{{printf "%.2f" .Statistics.ProcessingTime}} seconds</td></tr>
        <tr><th>Total Markers</th><td>{{.Statistics.TotalMarkers}}</td></tr>
        <tr><th>Atomic Markers</th><td>{{.Statistics.AtomicMarkers}}</td></tr>
        <tr><th>Composite Markers</th><td>{{.Statistics.CompositeMarkers}}</td></tr>
        <tr><th>Average Confidence</th><td>{{printf "%.2f" .Statistics.AverageConfidence}}</td></tr>
    </table>
    
    {{if .Statistics.MarkerTypes}}
    <h2>Marker Types</h2>
    <table>
        <tr><th>Type</th><th>Count</th></tr>
        {{range $type, $count := .Statistics.MarkerTypes}}
        <tr><td>{{$type}}</td><td>{{$count}}</td></tr>
        {{end}}
    </table>
    {{end}}
    
    {{if .Markers}}
    <h2>Detailed Findings</h2>
    {{range .Markers}}
    <div class="marker level-{{.Level}}">
        <strong>{{.Type}}</strong>
        <span class="confidence-{{confidenceClass .Confidence}}">({{printf "%.2f" .Confidence}})</span><br>
        <em>"{{.TextSpan}}"</em><br>
        {{if .Context}}<small>Context: {{.Context}}</small><br>{{end}}
        {{if .RuleID}}<small>Detected by: {{.RuleID}}</small>{{end}}
    </div>
    {{end}}
    {{end}}
    
    <hr>
    <p><small>Report generated by Semantic Analyzer v{{.Version}}</small></p>
</body>
</html>`
    
    // Create template with custom function
    funcMap := template.FuncMap{
        "confidenceClass": func(confidence float64) string {
            if confidence >= 0.8 {
                return "high"
            } else if confidence >= 0.5 {
                return "medium"
            }
            return "low"
        },
    }
    
    tmpl, err := template.New("html_report").Funcs(funcMap).Parse(htmlTemplate)
    if err != nil {
        return nil, err
    }
    
    data := g.prepareReportData(result)
    var buf bytes.Buffer
    if err := tmpl.Execute(&buf, data); err != nil {
        return nil, err
    }
    
    return buf.Bytes(), nil
}